### ISSUE TITLE
master detail for tow class entity

### ISSUE THREAD

**Issue by ebrahimrayatparvar** [DevExpress-Examples/a-master-detail-grid-with-entity-framework-objects-e417#14]
hi. i need master detail gridcontrol for 2 class entity.
I came up with a model class and made a list of those two classes. And I had to go to the grid but I didn't get an answer.

**Comment by AlexGreenZ** [comment]
Hello,

Thank you for reaching out to us. As for technical questions, it is better to address them directly to our R&D team via our Support Center ([www.devexpress.com/support/center](http://www.devexpress.com/support/center)). Feel free to describe your scenario in greater detail so that we can provide you with a suitable answer.
